### PR TITLE
feat: Add overall documentation structure

### PR DESCRIPTION
**Pull request by fghaas**
Group the documentation into four general sections:

* Concepts
* How-to guides
* Tutorials
* Reference

This approach follows the Diátaxis model, a widely adopted technical
documentation framework.

Reference:
https://diataxis.fr/

### CODE REVIEW

**Comment by evrardjp** [comment]
Any reason to keep this as draft?

**Comment by fghaas** [comment]
> Any reason to keep this as draft?

Well, yeah, I wanted to include one example for each category in. But maybe that's not realistic; we might as review this now.

**Comment by fghaas** [comment]
@evrardjp Let me know how you want to proceed here. You can either review this now and we can merge, or you can wait until some examples are in place.

**Comment by evrardjp** [comment]
@fghaas Thanks for the ping. I will review now.

**Review by evrardjp — APPROVED** [review]
Let's get the ball rolling.
@fghaas  can you merge?

**Comment by fghaas** [comment]
No need to; this PR was set to auto-merge upon approval once the tests passed. :)

**Pull request merged**
