### PR TITLE
feat: Add links to technical writing resources

### PR DESCRIPTION
**Pull request by fghaas**
Expand the contribution guide with a paragraph containing links to style guides, quality guidelines, and other resources helpful to
technical writers.

### CODE REVIEW

**Review by evrardjp — COMMENTED** [review]
Acceptable to me as a reference guide.
However, having 4 resources doesn't explain what's needed to have your documentation merged. 

I think that what you're saying here, inherently, is that we'll accept _any proposal_ and that your team will fix it to match _your criteria_. This is fine for me.

**Comment by fghaas** [comment]
> I think that what you're saying here, inherently, is that we'll accept any proposal and that your team will fix it to match your undocumented criteria. This is fine for me.

If "accept" means we'll merge it outright, then no. If "accept" means we'll be working with whoever submits the PR to get it into mergeable shape (not including only content, but also grammar, syntax, vocabulary, and style), then yes of course.

**Comment by evrardjp** [comment]
perfect, that's all I ask!

**Review by evrardjp — APPROVED** [review]
LGTM with the cotnext mentioned in this PR.

**Pull request merged**
